---
data_load:
  num_threads: 64

signal:
  sr: 16000
  duration: 0.5
  win_length: 400
  hop_length: 80
  n_fft: 512
  n_mels: 80

model:
  num_banks: 8
  hidden_units: 128
  num_highway: 2
  norm_type: 'ins'
  embedding_size: 16

# Path
logdir_path: 'logdir'
#logdir_path: '/data/private/voice-vector/logdir'

train:
  # path
  data_path: 'datasets/vcc2016_training'
  ckpt_prefix: 'model.ckpt'
  num_gpu: 1

  # train
  batch_size: 128
  margin: 0.2
  lr: 0.00005
  num_steps: 10000000
  save_per_step: 50000
  clip_value_max: 5.
  clip_value_min: -5.
  clip_norm: 100

eval:
  # path
  data_path: 'datasets/vcc2016_evaluation'

  # test
  batch_size: 128

embed:
  # path
  data_path: 'datasets/vcc2016_evaluation'

  # test
  batch_size: 128