---
data_load:
  num_threads: 64

signal:
  sr: 16000
  duration: 0.1
  win_length: 400
  hop_length: 80
  n_fft: 512

model:
  num_banks: 16
  hidden_units: 512
  num_highway: 8
  norm_type: 'ins'
  embedding_size: 256

# Path
logdir_path: '/data/private/voice-vector/logdir'
#logdir_path: 'logdir'

train:
  # path
  data_path: 'datasets/vcc2016_training'
  ckpt_prefix: 'model.ckpt'

  # train
  batch_size: 32
  margin: 0.2
  lr: 0.00005
  num_steps: 10000000
  save_per_step: 50000
  clip_value_max: 5.
  clip_value_min: -5.
  clip_norm: 100

embed:
  # path
  data_path: 'datasets/vcc2016_training'

  # test
  batch_size: 100