---
batch_1:
  logdir_path: 'logdir'
  train:
    batch_size: 1
  embed:
    batch_size: 1000
---
batch_2:
  train:
    batch_size: 2
---
batch_4:
  logdir_path: 'logdir'
  train:
    batch_size: 4
  embed:
    batch_size: 1000
