---
baseline:
  signal:
    duration: 0.5
  model:
    embedding_size: 10
  embed:
    batch_size: 512
---
baseline_2s:
  signal:
    duration: 2
  model:
    embedding_size: 10
  train:
    batch_size: 32
  embed:
    batch_size: 512
---
voxceleb:
  train:
    data_path: '/data/public/rw/voxceleb/speaker_data'
  eval:
    data_path: '/data/public/rw/voxceleb/speaker_data'
  embed:
    data_path: '/data/public/rw/voxceleb/speaker_data'
  batch_size: 32