---
baseline:
  model:
    embedding_size: 16
  train:
    num_gpu: 4
  embed:
    batch_size: 512
---
baseline_2s:
  signal:
    duration: 2
  train:
    batch_size: 32
  embed:
    batch_size: 512
---
voxceleb:
#  model:
#    hidden_units: 512
  train:
    batch_size: 128
    data_path: '/data/public/rw/voxceleb_resampled/speaker_data'
    num_gpu: 4
    lr: 0.00005
  eval:
    data_path: '/data/public/rw/voxceleb_resampled/speaker_data'
  embed:
    data_path: '/data/public/rw/voxceleb_resampled/speaker_data'
---
voxceleb_norm:
  train:
    batch_size: 128
    data_path: '/data/public/rw/voxceleb_norm'
    num_gpu: 4
    lr: 0.00005
  eval:
    data_path: '/data/public/rw/voxceleb_norm'
  embed:
#    data_path: '/data/public/rw/voxceleb_norm'
    data_path: '/voice-vector/datasets/vcc2016_evaluation'
