---
baseline:
  model:
    embedding_size: 16
  train:
    num_gpu: 4
  embed:
    batch_size: 512
---
baseline_2s:
  signal:
    duration: 2
  train:
    batch_size: 32
  embed:
    batch_size: 512
---
voxceleb:
  model:
    hidden_units: 512
  train:
    data_path: 'datasets/voxceleb_resampled/speaker_data'
    num_gpu: 4
  eval:
    data_path: 'datasets/voxceleb_resampled/speaker_data'
  embed:
    data_path: 'datasets/voxceleb_resampled/speaker_data'