---
baseline:
  signal:
    duration: 0.5
  model:
    embedding_size: 10
  embed:
    batch_size: 512
---
baseline_2s:
  signal:
    duration: 2
  model:
    embedding_size: 10
  train:
    batch_size: 32
  embed:
    data_path: 'datasets/timit/TIMIT/TEST'
    batch_size: 8